language: node_js
node_js:
  - lts/*

cache:
  directories:
    - "./node_modules"
  yarn: true

git:
  depth: false

install:
  - yarn 

deploy:
  provider: script
  skip_cleanup: true
  script: yarn release
  on:
    branch: release